<MODULEFILE>./core/modules/check_image_set.sh</MODULEFILE><ERRORDESCRIPTION>find:warning:youhavespecifiedthe-maxdepthoptionafteranon-optionargument-type,butoptionsarenotpositional(-maxdepthaffectstestsspecifiedbeforeitaswellasthosespecifiedafterit).Pleasespecifyoptionsbeforeotherarguments.</ERRORDESCRIPTION><ERRORTIME>201211211753</ERRORTIME><MODULEOUT>&lt;!- COMPLETEFILECHECK=0 -&gt; &lt;!- TIFFDIRLASTMODIFIED=1 -&gt; &lt;!- TIFFCOUNT=0 -&gt; &lt;status action="check_image_set"&gt;paused &lt;message&gt; Paused because the TIFF directory contains no tif images. &lt;/message&gt; &lt;/status&gt;</MODULEOUT>
<MODULEFILE>./core/modules/check_image_set.sh</MODULEFILE><ERRORDESCRIPTION>find:warning:youhavespecifiedthe-maxdepthoptionafteranon-optionargument-type,butoptionsarenotpositional(-maxdepthaffectstestsspecifiedbeforeitaswellasthosespecifiedafterit).Pleasespecifyoptionsbeforeotherarguments.</ERRORDESCRIPTION><ERRORTIME>201303051757</ERRORTIME><MODULEOUT>&lt;!- COMPLETEFILECHECK=0 -&gt; &lt;!- TIFFDIRLASTMODIFIED=1 -&gt; &lt;!- TIFFCOUNT=0 -&gt; &lt;status action="check_image_set"&gt;paused &lt;message&gt; Paused because the TIFF directory contains no tif images. &lt;/message&gt; &lt;/status&gt;</MODULEOUT>
<MODULEFILE></MODULEFILE><ERRORDESCRIPTION>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/functions/execute_ibrain_module.sh:12:main:notfound</ERRORDESCRIPTION><ERRORTIME>201309091351</ERRORTIME><MODULEOUT></MODULEOUT>
<MODULEFILE></MODULEFILE><ERRORDESCRIPTION>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/functions/execute_ibrain_module.sh:12:main:notfound</ERRORDESCRIPTION><ERRORTIME>201309091353</ERRORTIME><MODULEOUT></MODULEOUT>
<MODULEFILE>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/modules/create_mips.sh</MODULEFILE><ERRORDESCRIPTION>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/functions/execute_ibrain_module.sh:12:main:notfound</ERRORDESCRIPTION><ERRORTIME>201309091354</ERRORTIME><MODULEOUT></MODULEOUT>
<MODULEFILE>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/modules/run_pipes.sh</MODULEFILE><ERRORDESCRIPTION>Traceback(mostrecentcalllast):File"<stdin>",line5,in<module>ImportError:cannotimportnameNORM_QUEUE</ERRORDESCRIPTION><ERRORTIME>201309171512</ERRORTIME><MODULEOUT></MODULEOUT>
<MODULEFILE>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/modules/run_pipes.sh</MODULEFILE><ERRORDESCRIPTION>Traceback(mostrecentcalllast):File"<stdin>",line4,in<module>File"ext_path.py",line36,in<module>extend_sys_path(__file__,['lib/python'])File"ext_path.py",line29,inextend_sys_pathroot_path=get_root_path(module_path)File"ext_path.py",line21,inget_root_pathraiseException('Failedtosetrootpath')Exception:Failedtosetrootpath</ERRORDESCRIPTION><ERRORTIME>201309171521</ERRORTIME><MODULEOUT></MODULEOUT>
<MODULEFILE>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/modules/run_pipes.sh</MODULEFILE><ERRORDESCRIPTION>Traceback(mostrecentcalllast):File"<stdin>",line4,in<module>File"ext_path.py",line36,in<module>extend_sys_path(__file__,['lib/python'])File"ext_path.py",line29,inextend_sys_pathroot_path=get_root_path(module_path)File"ext_path.py",line21,inget_root_pathraiseException('Failedtosetrootpath')Exception:Failedtosetrootpath</ERRORDESCRIPTION><ERRORTIME>201309171524</ERRORTIME><MODULEOUT></MODULEOUT>
<MODULEFILE>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/modules/run_pipes.sh</MODULEFILE><ERRORDESCRIPTION>Traceback(mostrecentcalllast):File"<stdin>",line5,in<module>ImportError:cannotimportnameNORM_QUEUE</ERRORDESCRIPTION><ERRORTIME>201309171525</ERRORTIME><MODULEOUT>!</MODULEOUT>
<MODULEFILE>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/modules/run_pipes.sh</MODULEFILE><ERRORDESCRIPTION>Traceback(mostrecentcalllast):File"<stdin>",line5,in<module>ImportError:cannotimportnameNORM_QUEUE</ERRORDESCRIPTION><ERRORTIME>201309171525</ERRORTIME><MODULEOUT>/home/yy/dev/imls/iBRAIN/iBRAIN</MODULEOUT>
<MODULEFILE>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/modules/run_pipes.sh</MODULEFILE><ERRORDESCRIPTION>Traceback(mostrecentcalllast):File"<stdin>",line5,in<module>ImportError:cannotimportnameNORM_QUEUE</ERRORDESCRIPTION><ERRORTIME>201309171526</ERRORTIME><MODULEOUT></MODULEOUT>
<MODULEFILE>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/modules/run_pipes.sh</MODULEFILE><ERRORDESCRIPTION>Traceback(mostrecentcalllast):File"<stdin>",line4,in<module>File"ext_path.py",line36,in<module>extend_sys_path(__file__,['lib/python'])File"ext_path.py",line29,inextend_sys_pathroot_path=get_root_path(module_path)File"ext_path.py",line21,inget_root_pathraiseException('Failedtosetrootpath')Exception:Failedtosetrootpath</ERRORDESCRIPTION><ERRORTIME>201309171526</ERRORTIME><MODULEOUT></MODULEOUT>
<MODULEFILE>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/modules/run_pipes.sh</MODULEFILE><ERRORDESCRIPTION>Traceback(mostrecentcalllast):File"<stdin>",line4,in<module>File"ext_path.py",line36,in<module>extend_sys_path(__file__,['lib/python'])File"ext_path.py",line29,inextend_sys_pathroot_path=get_root_path(module_path)File"ext_path.py",line21,inget_root_pathraiseException('Failedtosetrootpath')Exception:Failedtosetrootpath</ERRORDESCRIPTION><ERRORTIME>201309171527</ERRORTIME><MODULEOUT></MODULEOUT>
<MODULEFILE>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/modules/run_pipes.sh</MODULEFILE><ERRORDESCRIPTION>Traceback(mostrecentcalllast):File"<stdin>",line4,in<module>File"ext_path.py",line36,in<module>extend_sys_path(__file__,['lib/python'])File"ext_path.py",line29,inextend_sys_pathroot_path=get_root_path(module_path)File"ext_path.py",line21,inget_root_pathraiseException('Failedtosetrootpath')Exception:Failedtosetrootpath</ERRORDESCRIPTION><ERRORTIME>201309171528</ERRORTIME><MODULEOUT></MODULEOUT>
<MODULEFILE>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/modules/run_pipes.sh</MODULEFILE><ERRORDESCRIPTION>Traceback(mostrecentcalllast):File"<stdin>",line5,in<module>File"ext_path.py",line36,in<module>extend_sys_path(__file__,['lib/python'])File"ext_path.py",line29,inextend_sys_pathroot_path=get_root_path(module_path)File"ext_path.py",line21,inget_root_pathraiseException('Failedtosetrootpath')Exception:Failedtosetrootpath</ERRORDESCRIPTION><ERRORTIME>201309171528</ERRORTIME><MODULEOUT>!</MODULEOUT>
<MODULEFILE>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/modules/run_pipes.sh</MODULEFILE><ERRORDESCRIPTION>Traceback(mostrecentcalllast):File"<stdin>",line4,in<module>File"ext_path.py",line37,in<module>extend_sys_path(__file__,['lib/python'])File"ext_path.py",line30,inextend_sys_pathroot_path=get_root_path(module_path)File"ext_path.py",line22,inget_root_pathraiseException('Failedtosetrootpath')Exception:Failedtosetrootpath</ERRORDESCRIPTION><ERRORTIME>201309171528</ERRORTIME><MODULEOUT>!</MODULEOUT>
<MODULEFILE>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/modules/run_pipes.sh</MODULEFILE><ERRORDESCRIPTION>Traceback(mostrecentcalllast):File"<stdin>",line4,in<module>File"ext_path.py",line37,in<module>extend_sys_path(__file__,['lib/python'])File"ext_path.py",line30,inextend_sys_pathroot_path=get_root_path(module_path)File"ext_path.py",line22,inget_root_pathraiseException('Failedtosetrootpath')Exception:Failedtosetrootpath</ERRORDESCRIPTION><ERRORTIME>201309171528</ERRORTIME><MODULEOUT>!</MODULEOUT>
<MODULEFILE>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/modules/run_pipes.sh</MODULEFILE><ERRORDESCRIPTION>Traceback(mostrecentcalllast):File"<stdin>",line4,in<module>File"ext_path.py",line37,in<module>extend_sys_path(__file__,['lib/python'])File"ext_path.py",line30,inextend_sys_pathroot_path=get_root_path(module_path)File"ext_path.py",line22,inget_root_pathraiseException('Failedtosetrootpath')Exception:Failedtosetrootpath</ERRORDESCRIPTION><ERRORTIME>201309171528</ERRORTIME><MODULEOUT>!</MODULEOUT>
<MODULEFILE>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/modules/run_pipes.sh</MODULEFILE><ERRORDESCRIPTION>Traceback(mostrecentcalllast):File"<stdin>",line4,in<module>File"ext_path.py",line37,in<module>extend_sys_path(__file__,['lib/python'])File"ext_path.py",line30,inextend_sys_pathroot_path=get_root_path(module_path)File"ext_path.py",line22,inget_root_pathraiseException('Failedtosetrootpath')Exception:Failedtosetrootpath</ERRORDESCRIPTION><ERRORTIME>201309171528</ERRORTIME><MODULEOUT>!!</MODULEOUT>
<MODULEFILE>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/modules/run_pipes.sh</MODULEFILE><ERRORDESCRIPTION>Traceback(mostrecentcalllast):File"<stdin>",line4,in<module>File"ext_path.py",line37,in<module>extend_sys_path(__file__,['lib/python'])File"ext_path.py",line30,inextend_sys_pathroot_path=get_root_path(module_path)File"ext_path.py",line22,inget_root_pathraiseException('Failedtosetrootpath')Exception:Failedtosetrootpath</ERRORDESCRIPTION><ERRORTIME>201309171529</ERRORTIME><MODULEOUT>ext_path.pyc</MODULEOUT>
<MODULEFILE>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/modules/run_pipes.sh</MODULEFILE><ERRORDESCRIPTION>Traceback(mostrecentcalllast):File"<stdin>",line4,in<module>File"ext_path.py",line37,in<module>extend_sys_path(__file__,['lib/python'])File"ext_path.py",line30,inextend_sys_pathroot_path=get_root_path(module_path)File"ext_path.py",line18,inget_root_pathroot_path,module_path=module_path.rsplit(ROOT+'/',1)ValueError:needmorethan1valuetounpack</ERRORDESCRIPTION><ERRORTIME>201309171531</ERRORTIME><MODULEOUT></MODULEOUT>
<MODULEFILE>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/modules/run_pipes.sh</MODULEFILE><ERRORDESCRIPTION>Traceback(mostrecentcalllast):File"<stdin>",line4,in<module>File"ext_path.py",line37,in<module>extend_sys_path(__file__,['lib/python'])File"ext_path.py",line30,inextend_sys_pathroot_path=get_root_path(module_path)File"ext_path.py",line18,inget_root_pathroot_path,module_path=module_path.rsplit(root+'/',1)ValueError:needmorethan1valuetounpack</ERRORDESCRIPTION><ERRORTIME>201309171535</ERRORTIME><MODULEOUT></MODULEOUT>
<MODULEFILE>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/modules/run_pipes.sh</MODULEFILE><ERRORDESCRIPTION>Traceback(mostrecentcalllast):File"<stdin>",line4,in<module>File"ext_path.py",line38,in<module>extend_sys_path(__file__,['lib/python'])File"ext_path.py",line31,inextend_sys_pathroot_path=get_root_path(module_path)File"ext_path.py",line19,inget_root_pathroot_path,module_path=module_path.rsplit(root+'/',1)ValueError:needmorethan1valuetounpack</ERRORDESCRIPTION><ERRORTIME>201309171535</ERRORTIME><MODULEOUT>iBRAIN</MODULEOUT>
<MODULEFILE>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/modules/run_pipes.sh</MODULEFILE><ERRORDESCRIPTION>Traceback(mostrecentcalllast):File"<stdin>",line4,in<module>File"ext_path.py",line38,in<module>extend_sys_path(__file__,['lib/python'])File"ext_path.py",line31,inextend_sys_pathroot_path=get_root_path(module_path)File"ext_path.py",line19,inget_root_pathroot_path,module_path=module_path.rsplit(root+'/',1)ValueError:needmorethan1valuetounpack</ERRORDESCRIPTION><ERRORTIME>201309171536</ERRORTIME><MODULEOUT>ext_path.pyc</MODULEOUT>
<MODULEFILE>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/modules/run_pipes.sh</MODULEFILE><ERRORDESCRIPTION>Traceback(mostrecentcalllast):File"<stdin>",line4,in<module>File"ext_path.py",line38,in<module>extend_sys_path(__file__,['lib/python'])File"ext_path.py",line31,inextend_sys_pathroot_path=get_root_path(module_path)File"ext_path.py",line19,inget_root_pathroot_path,module_path=module_path.rsplit(root+'/',1)ValueError:needmorethan1valuetounpack</ERRORDESCRIPTION><ERRORTIME>201309171536</ERRORTIME><MODULEOUT>ext_path.pyc</MODULEOUT>
<MODULEFILE>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/modules/run_pipes.sh</MODULEFILE><ERRORDESCRIPTION>Traceback(mostrecentcalllast):File"<stdin>",line5,in<module>ImportError:cannotimportnameNORM_QUEUE</ERRORDESCRIPTION><ERRORTIME>201309172011</ERRORTIME><MODULEOUT></MODULEOUT>
<MODULEFILE>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/modules/run_pipes.sh</MODULEFILE><ERRORDESCRIPTION>Traceback(mostrecentcalllast):File"<stdin>",line5,in<module>ImportError:cannotimportnameNORM_QUEUE</ERRORDESCRIPTION><ERRORTIME>201309172016</ERRORTIME><MODULEOUT></MODULEOUT>
<MODULEFILE>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/modules/run_pipes.sh</MODULEFILE><ERRORDESCRIPTION>Traceback(mostrecentcalllast):File"<stdin>",line5,in<module>ImportError:cannotimportnameNORM_QUEUE</ERRORDESCRIPTION><ERRORTIME>201309172032</ERRORTIME><MODULEOUT></MODULEOUT>
<MODULEFILE>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/modules/run_pipes.sh</MODULEFILE><ERRORDESCRIPTION>Traceback(mostrecentcalllast):File"<stdin>",line7,in<module>TypeError:__init__()takesexactly3arguments(1given)</ERRORDESCRIPTION><ERRORTIME>201309172034</ERRORTIME><MODULEOUT></MODULEOUT>
<MODULEFILE>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/modules/run_pipes.sh</MODULEFILE><ERRORDESCRIPTION>Traceback(mostrecentcalllast):File"<stdin>",line7,in<module>TypeError:__init__()takesexactly3arguments(1given)</ERRORDESCRIPTION><ERRORTIME>201309172035</ERRORTIME><MODULEOUT></MODULEOUT>
<MODULEFILE>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/modules/run_pipes.sh</MODULEFILE><ERRORDESCRIPTION>Traceback (most recent call last): File "<stdin>", line 7, in <module> TypeError: __init__() takes exactly 3 arguments (1 given)</ERRORDESCRIPTION><ERRORTIME>201309172035</ERRORTIME><MODULEOUT></MODULEOUT>
<MODULEFILE>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/modules/run_pipes.sh</MODULEFILE><ERRORDESCRIPTION>Traceback (most recent call last): File "<stdin>", line 7, in <module> TypeError: __init__() takes exactly 3 arguments (1 given)</ERRORDESCRIPTION><ERRORTIME>201309172037</ERRORTIME><MODULEOUT></MODULEOUT>
<MODULEFILE>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/modules/run_pipes.sh</MODULEFILE><ERRORDESCRIPTION>Traceback (most recent call last): File "<stdin>", line 7, in <module> TypeError: __init__() takes exactly 3 arguments (1 given)</ERRORDESCRIPTION><ERRORTIME>201309172038</ERRORTIME><MODULEOUT></MODULEOUT>
<MODULEFILE>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/modules/run_pipes.sh</MODULEFILE><ERRORDESCRIPTION>Traceback (most recent call last): File "<stdin>", line 7, in <module> TypeError: __init__() takes exactly 3 arguments (1 given)</ERRORDESCRIPTION><ERRORTIME>201309172038</ERRORTIME><MODULEOUT></MODULEOUT>
<MODULEFILE>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/modules/run_pipes.sh</MODULEFILE><ERRORDESCRIPTION>Traceback (most recent call last): File "<stdin>", line 7, in <module> TypeError: __init__() takes exactly 3 arguments (1 given)</ERRORDESCRIPTION><ERRORTIME>201309172039</ERRORTIME><MODULEOUT></MODULEOUT>
<MODULEFILE>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/modules/run_pipes.sh</MODULEFILE><ERRORDESCRIPTION>Traceback (most recent call last): File "<stdin>", line 7, in <module> TypeError: __init__() takes exactly 3 arguments (1 given)</ERRORDESCRIPTION><ERRORTIME>201309172039</ERRORTIME><MODULEOUT></MODULEOUT>
<MODULEFILE>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/modules/run_pipes.sh</MODULEFILE><ERRORDESCRIPTION>Traceback (most recent call last): File "&lt;stdin&gt;", line 7, in &lt;module&gt; TypeError: __init__() takes exactly 3 arguments (1 given)</ERRORDESCRIPTION><ERRORTIME>201309172040</ERRORTIME><MODULEOUT></MODULEOUT>
<MODULEFILE>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/modules/run_pipes.sh</MODULEFILE><ERRORDESCRIPTION>09-17 20:44 brainy.lsf WARNING Failed to locate LSF commands like bjobs, bsub, bkill. Is LSF installed? Traceback (most recent call last): File "&lt;stdin&gt;", line 15, in &lt;module&gt; File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 299, in process_pipelines for pipeline in self.pipelines: File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 214, in pipelines definition = Pipe.parse_definition(definition_filename) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/pipette/__init__.py", line 136, in parse_definition with open(definition_filepath) as definition_file: IOError: [Errno 2] No such file or directory: 'testPipe.json'</ERRORDESCRIPTION><ERRORTIME>201309172044</ERRORTIME><MODULEOUT></MODULEOUT>
<MODULEFILE>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/modules/run_pipes.sh</MODULEFILE><ERRORDESCRIPTION>Traceback (most recent call last): File "&lt;stdin&gt;", line 15, in &lt;module&gt; File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 299, in process_pipelines for pipeline in self.pipelines: File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 214, in pipelines definition = Pipe.parse_definition(definition_filename) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/pipette/__init__.py", line 136, in parse_definition with open(definition_filepath) as definition_file: IOError: [Errno 2] No such file or directory: 'testPipe.json'</ERRORDESCRIPTION><ERRORTIME>201309172048</ERRORTIME><MODULEOUT></MODULEOUT>
<MODULEFILE>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/modules/run_pipes.sh</MODULEFILE><ERRORDESCRIPTION>Traceback (most recent call last): File "&lt;stdin&gt;", line 15, in &lt;module&gt; File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 299, in process_pipelines for pipeline in self.pipelines: File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 214, in pipelines definition = Pipe.parse_definition(definition_filename) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/pipette/__init__.py", line 136, in parse_definition with open(definition_filepath) as definition_file: IOError: [Errno 2] No such file or directory: 'testPipe.json'</ERRORDESCRIPTION><ERRORTIME>201309172102</ERRORTIME><MODULEOUT></MODULEOUT>
<MODULEFILE>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/modules/run_pipes.sh</MODULEFILE><ERRORDESCRIPTION>Traceback (most recent call last): File "&lt;stdin&gt;", line 15, in &lt;module&gt; File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 302, in process_pipelines for pipeline in self.pipelines: File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 217, in pipelines definition = Pipe.parse_definition(definition_filename) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/pipette/__init__.py", line 137, in parse_definition definition = json.load(definition_file) File "/usr/lib/python2.7/json/__init__.py", line 278, in load **kw) File "/usr/lib/python2.7/json/__init__.py", line 326, in loads return _default_decoder.decode(s) File "/usr/lib/python2.7/json/decoder.py", line 366, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end()) File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode obj, end = self.scan_once(s, idx) ValueError: Expecting property name: line 2 column 5 (char 6)</ERRORDESCRIPTION><ERRORTIME>201309172105</ERRORTIME><MODULEOUT></MODULEOUT>
<MODULEFILE>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/modules/run_pipes.sh</MODULEFILE><ERRORDESCRIPTION>Traceback (most recent call last): File "&lt;stdin&gt;", line 15, in &lt;module&gt; File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 302, in process_pipelines for pipeline in self.pipelines: File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 217, in pipelines definition = Pipe.parse_definition(definition_filename) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/pipette/__init__.py", line 141, in parse_definition error.message) IOError: JSON parsing error: Expecting property name: line 2 column 5 (char 6)</ERRORDESCRIPTION><ERRORTIME>201309172108</ERRORTIME><MODULEOUT></MODULEOUT>
<MODULEFILE>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/modules/run_pipes.sh</MODULEFILE><ERRORDESCRIPTION>Traceback (most recent call last): File "&lt;stdin&gt;", line 15, in &lt;module&gt; File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 302, in process_pipelines for pipeline in self.pipelines: File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 217, in pipelines definition = Pipe.parse_definition(definition_filename) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/pipette/__init__.py", line 141, in parse_definition error.message) IOError: JSON parsing error. Expecting property name: line 2 column 5 (char 6)</ERRORDESCRIPTION><ERRORTIME>201309172108</ERRORTIME><MODULEOUT></MODULEOUT>
<MODULEFILE>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/modules/run_pipes.sh</MODULEFILE><ERRORDESCRIPTION>Traceback (most recent call last): File "&lt;stdin&gt;", line 15, in &lt;module&gt; File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 302, in process_pipelines for pipeline in self.pipelines: File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 217, in pipelines definition = Pipe.parse_definition(definition_filename) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/pipette/__init__.py", line 141, in parse_definition (definition_file, error.message)) IOError: JSON parsing error in: "&lt;open file '../project/PIPES/testPipe.json', mode 'r' at 0x7ff16b9b4930&gt;". Expecting property name: line 2 column 5 (char 6)</ERRORDESCRIPTION><ERRORTIME>201309172108</ERRORTIME><MODULEOUT></MODULEOUT>
<MODULEFILE>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/modules/run_pipes.sh</MODULEFILE><ERRORDESCRIPTION>Traceback (most recent call last): File "&lt;stdin&gt;", line 15, in &lt;module&gt; File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 302, in process_pipelines for pipeline in self.pipelines: File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 217, in pipelines definition = Pipe.parse_definition(definition_filename) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/pipette/__init__.py", line 141, in parse_definition (definition_filepath, error.message)) IOError: JSON parsing error in: "../project/PIPES/testPipe.json". Expecting property name: line 2 column 5 (char 6)</ERRORDESCRIPTION><ERRORTIME>201309172109</ERRORTIME><MODULEOUT></MODULEOUT>
<MODULEFILE>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/modules/run_pipes.sh</MODULEFILE><ERRORDESCRIPTION>Traceback (most recent call last): File "&lt;stdin&gt;", line 15, in &lt;module&gt; File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 302, in process_pipelines for pipeline in self.pipelines: File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 217, in pipelines definition = Pipe.parse_definition(definition_filename) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/pipette/__init__.py", line 142, in parse_definition definition = json.load(json_data) File "/usr/lib/python2.7/json/__init__.py", line 274, in load return loads(fp.read(), AttributeError: 'str' object has no attribute 'read'</ERRORDESCRIPTION><ERRORTIME>201309172115</ERRORTIME><MODULEOUT></MODULEOUT>
<MODULEFILE>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/modules/run_pipes.sh</MODULEFILE><ERRORDESCRIPTION>Traceback (most recent call last): File "&lt;stdin&gt;", line 15, in &lt;module&gt; File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 302, in process_pipelines for pipeline in self.pipelines: File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 218, in pipelines cls = self.get_class(definition['type']) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 207, in get_class return getattr(self.pipes_namespace, pipe_type) AttributeError: 'module' object has no attribute 'CellProfiller.Pipe'</ERRORDESCRIPTION><ERRORTIME>201309172116</ERRORTIME><MODULEOUT></MODULEOUT>
<MODULEFILE>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/modules/run_pipes.sh</MODULEFILE><ERRORDESCRIPTION>Traceback (most recent call last): File "&lt;stdin&gt;", line 15, in &lt;module&gt; File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 302, in process_pipelines for pipeline in self.pipelines: File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 218, in pipelines cls = self.get_class(definition['type']) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 207, in get_class return getattr(self.pipes_namespace, pipe_type) AttributeError: 'module' object has no attribute 'CellProfiller.CellProfillerPipe'</ERRORDESCRIPTION><ERRORTIME>201309172125</ERRORTIME><MODULEOUT></MODULEOUT>
<MODULEFILE>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/modules/run_pipes.sh</MODULEFILE><ERRORDESCRIPTION>Traceback (most recent call last): File "&lt;stdin&gt;", line 15, in &lt;module&gt; File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 305, in process_pipelines for pipeline in self.pipelines: File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 221, in pipelines cls = self.get_class(definition['type']) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 209, in get_class module = __import__(module_name) ImportError: No module named CellProfiller</ERRORDESCRIPTION><ERRORTIME>201309172129</ERRORTIME><MODULEOUT></MODULEOUT>
<MODULEFILE>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/modules/run_pipes.sh</MODULEFILE><ERRORDESCRIPTION>Traceback (most recent call last): File "&lt;stdin&gt;", line 15, in &lt;module&gt; File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 306, in process_pipelines for pipeline in self.pipelines: File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 222, in pipelines cls = self.get_class(definition['type']) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 210, in get_class module = __import__(module_name) ImportError: No module named CellProfiller</ERRORDESCRIPTION><ERRORTIME>201309172130</ERRORTIME><MODULEOUT>brainy.pipes.CellProfiller</MODULEOUT>
<MODULEFILE>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/modules/run_pipes.sh</MODULEFILE><ERRORDESCRIPTION>Traceback (most recent call last): File "&lt;stdin&gt;", line 15, in &lt;module&gt; File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 306, in process_pipelines for pipeline in self.pipelines: File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 222, in pipelines cls = self.get_class(definition['type']) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 211, in get_class return getattr(module, class_name) AttributeError: 'module' object has no attribute 'Pipe'</ERRORDESCRIPTION><ERRORTIME>201309172132</ERRORTIME><MODULEOUT>brainy.pipes.CellProfiler</MODULEOUT>
<MODULEFILE>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/modules/run_pipes.sh</MODULEFILE><ERRORDESCRIPTION>Traceback (most recent call last): File "&lt;stdin&gt;", line 15, in &lt;module&gt; File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 306, in process_pipelines for pipeline in self.pipelines: File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 222, in pipelines cls = self.get_class(definition['type']) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 211, in get_class return getattr(module, class_name) AttributeError: 'module' object has no attribute 'Pipe'</ERRORDESCRIPTION><ERRORTIME>201309172133</ERRORTIME><MODULEOUT>['BrainyModule', 'BrainyPipe', 'BrainyProcess', '__builtins__', '__doc__', '__file__', '__name__', '__package__', '__path__', 'flags', 'get_config', 'invoke', 'log', 'lsf', 'modules', 'pipes']</MODULEOUT>
<MODULEFILE>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/modules/run_pipes.sh</MODULEFILE><ERRORDESCRIPTION>Traceback (most recent call last): File "&lt;stdin&gt;", line 15, in &lt;module&gt; File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 306, in process_pipelines for pipeline in self.pipelines: File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 224, in pipelines pipes[definition['name']] = cls(self, definition) TypeError: __init__() takes exactly 1 argument (3 given)</ERRORDESCRIPTION><ERRORTIME>201309172134</ERRORTIME><MODULEOUT>['BrainyPipe', 'BrainyProcess', 'Pipe', 'PreCluster', '__builtins__', '__doc__', '__file__', '__name__', '__package__']</MODULEOUT>
<MODULEFILE>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/modules/run_pipes.sh</MODULEFILE><ERRORDESCRIPTION>Traceback (most recent call last): File "&lt;stdin&gt;", line 15, in &lt;module&gt; File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 305, in process_pipelines for pipeline in self.pipelines: File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 223, in pipelines pipes[definition['name']] = cls(self, definition) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 146, in __init__ super(Pipe, self).__init__(definition_filepath) TypeError: object.__init__() takes no parameters</ERRORDESCRIPTION><ERRORTIME>201309172144</ERRORTIME><MODULEOUT></MODULEOUT>
<MODULEFILE>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/modules/run_pipes.sh</MODULEFILE><ERRORDESCRIPTION>Traceback (most recent call last): File "&lt;stdin&gt;", line 15, in &lt;module&gt; File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 305, in process_pipelines for pipeline in self.pipelines: File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 223, in pipelines pipes[definition['name']] = cls(self, definition) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 146, in __init__ super(Pipe, self).__init__(definition) TypeError: object.__init__() takes no parameters</ERRORDESCRIPTION><ERRORTIME>201309172146</ERRORTIME><MODULEOUT></MODULEOUT>
<MODULEFILE>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/modules/run_pipes.sh</MODULEFILE><ERRORDESCRIPTION>Traceback (most recent call last): File "&lt;stdin&gt;", line 15, in &lt;module&gt; File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 305, in process_pipelines for pipeline in self.pipelines: File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 223, in pipelines pipes[definition['name']] = cls(self, definition) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 146, in __init__ super(Pipe, self).__init__(definition) TypeError: object.__init__() takes no parameters</ERRORDESCRIPTION><ERRORTIME>201309172148</ERRORTIME><MODULEOUT></MODULEOUT>
<MODULEFILE>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/modules/run_pipes.sh</MODULEFILE><ERRORDESCRIPTION>Traceback (most recent call last): File "&lt;stdin&gt;", line 15, in &lt;module&gt; File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 305, in process_pipelines for pipeline in self.pipelines: File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 223, in pipelines pipes[definition['name']] = cls(self, definition) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 146, in __init__ super(Pipe, self).__init__(definition) TypeError: object.__init__() takes no parameters</ERRORDESCRIPTION><ERRORTIME>201309172148</ERRORTIME><MODULEOUT></MODULEOUT>
<MODULEFILE>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/modules/run_pipes.sh</MODULEFILE><ERRORDESCRIPTION>Traceback (most recent call last): File "&lt;stdin&gt;", line 15, in &lt;module&gt; File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 305, in process_pipelines for pipeline in self.pipelines: File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 220, in pipelines definition = Pipe.parse_definition(definition_filename) NameError: global name 'Pipe' is not defined</ERRORDESCRIPTION><ERRORTIME>201309172150</ERRORTIME><MODULEOUT></MODULEOUT>
<MODULEFILE>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/modules/run_pipes.sh</MODULEFILE><ERRORDESCRIPTION>Traceback (most recent call last): File "&lt;stdin&gt;", line 15, in &lt;module&gt; File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 305, in process_pipelines for pipeline in self.pipelines: File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 223, in pipelines pipes[definition['name']] = cls(self, definition) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 146, in __init__ super(pipette.Pipe, self).__init__(definition) TypeError: object.__init__() takes no parameters</ERRORDESCRIPTION><ERRORTIME>201309172151</ERRORTIME><MODULEOUT></MODULEOUT>
<MODULEFILE>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/modules/run_pipes.sh</MODULEFILE><ERRORDESCRIPTION>Traceback (most recent call last): File "&lt;stdin&gt;", line 15, in &lt;module&gt; File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 305, in process_pipelines for pipeline in self.pipelines: File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 223, in pipelines pipes[definition['name']] = cls(self, definition) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 146, in __init__ super(BrainyPipe, self).__init__(definition) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/pipette/__init__.py", line 129, in __init__ self.chain = list(self.bake_process()) AttributeError: 'Pipe' object has no attribute 'bake_process'</ERRORDESCRIPTION><ERRORTIME>201309172152</ERRORTIME><MODULEOUT></MODULEOUT>
<MODULEFILE>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/modules/run_pipes.sh</MODULEFILE><ERRORDESCRIPTION>Traceback (most recent call last): File "&lt;stdin&gt;", line 15, in &lt;module&gt; File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 305, in process_pipelines for pipeline in self.pipelines: File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 223, in pipelines pipes[definition['name']] = cls(self, definition) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 146, in __init__ super(BrainyPipe, self).__init__(definition) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/pipette/__init__.py", line 129, in __init__ self.chain = list(self.bake_processes()) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/pipette/__init__.py", line 157, in bake_processes process = self.instantiate_process(process_description) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 152, in instantiate_process process = super(pipette.Pipe, self).instantiate_process( AttributeError: 'super' object has no attribute 'instantiate_process'</ERRORDESCRIPTION><ERRORTIME>201309172153</ERRORTIME><MODULEOUT></MODULEOUT>
<MODULEFILE>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/modules/run_pipes.sh</MODULEFILE><ERRORDESCRIPTION>Traceback (most recent call last): File "&lt;stdin&gt;", line 15, in &lt;module&gt; File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 305, in process_pipelines for pipeline in self.pipelines: File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 223, in pipelines pipes[definition['name']] = cls(self, definition) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 146, in __init__ super(BrainyPipe, self).__init__(definition) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/pipette/__init__.py", line 129, in __init__ self.chain = list(self.bake_processes()) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/pipette/__init__.py", line 157, in bake_processes process = self.instantiate_process(process_description) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 153, in instantiate_process process_description, default_type) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/pipette/__init__.py", line 169, in instantiate_process process_description.get('type', default_type)) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/pipette/__init__.py", line 164, in find_process_class return getattr(self.process_namespace, process_type) AttributeError: 'str' object has no attribute 'CellProfiler.PreCluster'</ERRORDESCRIPTION><ERRORTIME>201309172155</ERRORTIME><MODULEOUT></MODULEOUT>
<MODULEFILE>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/modules/run_pipes.sh</MODULEFILE><ERRORDESCRIPTION>Traceback (most recent call last): File "&lt;stdin&gt;", line 15, in &lt;module&gt; File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 305, in process_pipelines for pipeline in self.pipelines: File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 223, in pipelines pipes[definition['name']] = cls(self, definition) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 146, in __init__ super(BrainyPipe, self).__init__(definition) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/pipette/__init__.py", line 129, in __init__ self.chain = list(self.bake_processes()) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/pipette/__init__.py", line 157, in bake_processes process = self.instantiate_process(process_description) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 153, in instantiate_process process_description, default_type) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/pipette/__init__.py", line 172, in instantiate_process process_description.get('type', default_type)) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/pipette/__init__.py", line 166, in find_process_class module = __import__(module_name, {}, {}, [class_name]) ImportError: No module named pippete.CellProfiler</ERRORDESCRIPTION><ERRORTIME>201309172156</ERRORTIME><MODULEOUT></MODULEOUT>
<MODULEFILE>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/modules/run_pipes.sh</MODULEFILE><ERRORDESCRIPTION>Traceback (most recent call last): File "&lt;stdin&gt;", line 15, in &lt;module&gt; File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 305, in process_pipelines for pipeline in self.pipelines: File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 223, in pipelines pipes[definition['name']] = cls(self, definition) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 146, in __init__ super(BrainyPipe, self).__init__(definition) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/pipette/__init__.py", line 129, in __init__ self.chain = list(self.bake_processes()) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/pipette/__init__.py", line 157, in bake_processes process = self.instantiate_process(process_description) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 153, in instantiate_process process_description, default_type) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/pipette/__init__.py", line 172, in instantiate_process process_description.get('type', default_type)) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/pipette/__init__.py", line 166, in find_process_class module = __import__(module_name, {}, {}, [class_name]) ImportError: No module named pippete.CellProfiler</ERRORDESCRIPTION><ERRORTIME>201309172157</ERRORTIME><MODULEOUT></MODULEOUT>
<MODULEFILE>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/modules/run_pipes.sh</MODULEFILE><ERRORDESCRIPTION>Traceback (most recent call last): File "&lt;stdin&gt;", line 15, in &lt;module&gt; File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 306, in process_pipelines self.execute_pipeline(pipeline) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 313, in execute_pipeline pipeline.communicate() File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/pipette/__init__.py", line 179, in communicate self.chain = list(self.bake_processes()) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/pipette/__init__.py", line 160, in bake_processes process.parameters.update(default_parameters) AttributeError: 'NoneType' object has no attribute 'parameters'</ERRORDESCRIPTION><ERRORTIME>201309172159</ERRORTIME><MODULEOUT></MODULEOUT>
<MODULEFILE>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/modules/run_pipes.sh</MODULEFILE><ERRORDESCRIPTION>Traceback (most recent call last): File "&lt;stdin&gt;", line 15, in &lt;module&gt; File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 306, in process_pipelines self.execute_pipeline(pipeline) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 313, in execute_pipeline pipeline.communicate() File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/pipette/__init__.py", line 180, in communicate self.chain = list(self.bake_processes()) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/pipette/__init__.py", line 161, in bake_processes process.parameters.update(default_parameters) AttributeError: 'NoneType' object has no attribute 'parameters'</ERRORDESCRIPTION><ERRORTIME>201309172200</ERRORTIME><MODULEOUT>None</MODULEOUT>
<MODULEFILE>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/modules/run_pipes.sh</MODULEFILE><ERRORDESCRIPTION>Traceback (most recent call last): File "&lt;stdin&gt;", line 15, in &lt;module&gt; File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 306, in process_pipelines self.execute_pipeline(pipeline) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 313, in execute_pipeline pipeline.communicate() File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/pipette/__init__.py", line 179, in communicate self.chain = list(self.bake_processes()) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/pipette/__init__.py", line 160, in bake_processes process.parameters.update(default_parameters) AttributeError: 'NoneType' object has no attribute 'parameters'</ERRORDESCRIPTION><ERRORTIME>201309172200</ERRORTIME><MODULEOUT></MODULEOUT>
<MODULEFILE>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/modules/run_pipes.sh</MODULEFILE><ERRORDESCRIPTION>Traceback (most recent call last): File "&lt;stdin&gt;", line 15, in &lt;module&gt; File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 307, in process_pipelines self.execute_pipeline(pipeline) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 314, in execute_pipeline pipeline.communicate() File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/pipette/__init__.py", line 190, in communicate process.streams['output'] = pipe_streams['output'] KeyError: 'output'</ERRORDESCRIPTION><ERRORTIME>201309172201</ERRORTIME><MODULEOUT></MODULEOUT>
<MODULEFILE>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/modules/run_pipes.sh</MODULEFILE><ERRORDESCRIPTION>Traceback (most recent call last): File "&lt;stdin&gt;", line 15, in &lt;module&gt; File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 307, in process_pipelines self.execute_pipeline(pipeline) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 314, in execute_pipeline pipeline.communicate() File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/pipette/__init__.py", line 208, in communicate self.execute_process(process, pipe_parameters) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 162, in execute_process step_name = self.get_step_name(process.name) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 35, in name return self.parameters['name'] KeyError: 'name'</ERRORDESCRIPTION><ERRORTIME>201309172202</ERRORTIME><MODULEOUT></MODULEOUT>
<MODULEFILE>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/modules/run_pipes.sh</MODULEFILE><ERRORDESCRIPTION>Traceback (most recent call last): File "&lt;stdin&gt;", line 15, in &lt;module&gt; File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 307, in process_pipelines self.execute_pipeline(pipeline) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 314, in execute_pipeline pipeline.communicate() File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/pipette/__init__.py", line 208, in communicate self.execute_process(process, pipe_parameters) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 162, in execute_process step_name = self.get_step_name(process.name) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 35, in name return self.parameters['name'] KeyError: 'name'</ERRORDESCRIPTION><ERRORTIME>201309172203</ERRORTIME><MODULEOUT></MODULEOUT>
<MODULEFILE>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/modules/run_pipes.sh</MODULEFILE><ERRORDESCRIPTION>Traceback (most recent call last): File "&lt;stdin&gt;", line 15, in &lt;module&gt; File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 307, in process_pipelines self.execute_pipeline(pipeline) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 314, in execute_pipeline pipeline.communicate() File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/pipette/__init__.py", line 182, in communicate self.chain = list(self.bake_processes()) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/pipette/__init__.py", line 157, in bake_processes process = self.instantiate_process(process_description) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 153, in instantiate_process process_description, default_type) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/pipette/__init__.py", line 174, in instantiate_process default_process_name = process.__class__.to_lower() AttributeError: type object 'PreCluster' has no attribute 'to_lower'</ERRORDESCRIPTION><ERRORTIME>201309172209</ERRORTIME><MODULEOUT></MODULEOUT>
<MODULEFILE>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/modules/run_pipes.sh</MODULEFILE><ERRORDESCRIPTION>Traceback (most recent call last): File "&lt;stdin&gt;", line 15, in &lt;module&gt; File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 307, in process_pipelines self.execute_pipeline(pipeline) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 314, in execute_pipeline pipeline.communicate() File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/pipette/__init__.py", line 182, in communicate self.chain = list(self.bake_processes()) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/pipette/__init__.py", line 157, in bake_processes process = self.instantiate_process(process_description) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 153, in instantiate_process process_description, default_type) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/pipette/__init__.py", line 174, in instantiate_process default_process_name = process.__class__.lower() AttributeError: type object 'PreCluster' has no attribute 'lower'</ERRORDESCRIPTION><ERRORTIME>201309172209</ERRORTIME><MODULEOUT></MODULEOUT>
<MODULEFILE>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/modules/run_pipes.sh</MODULEFILE><ERRORDESCRIPTION>Traceback (most recent call last): File "&lt;stdin&gt;", line 15, in &lt;module&gt; File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 307, in process_pipelines self.execute_pipeline(pipeline) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 314, in execute_pipeline pipeline.communicate() File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/pipette/__init__.py", line 182, in communicate self.chain = list(self.bake_processes()) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/pipette/__init__.py", line 157, in bake_processes process = self.instantiate_process(process_description) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 153, in instantiate_process process_description, default_type) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/pipette/__init__.py", line 174, in instantiate_process default_process_name = process.__class__.tolower() AttributeError: type object 'PreCluster' has no attribute 'tolower'</ERRORDESCRIPTION><ERRORTIME>201309172209</ERRORTIME><MODULEOUT></MODULEOUT>
<MODULEFILE>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/modules/run_pipes.sh</MODULEFILE><ERRORDESCRIPTION>Traceback (most recent call last): File "&lt;stdin&gt;", line 15, in &lt;module&gt; File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 307, in process_pipelines self.execute_pipeline(pipeline) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 314, in execute_pipeline pipeline.communicate() File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/pipette/__init__.py", line 182, in communicate self.chain = list(self.bake_processes()) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/pipette/__init__.py", line 157, in bake_processes process = self.instantiate_process(process_description) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 153, in instantiate_process process_description, default_type) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/pipette/__init__.py", line 174, in instantiate_process default_process_name = process.__class__.__name__.tolower() AttributeError: 'str' object has no attribute 'tolower'</ERRORDESCRIPTION><ERRORTIME>201309172209</ERRORTIME><MODULEOUT></MODULEOUT>
<MODULEFILE>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/modules/run_pipes.sh</MODULEFILE><ERRORDESCRIPTION>Traceback (most recent call last): File "&lt;stdin&gt;", line 15, in &lt;module&gt; File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 307, in process_pipelines self.execute_pipeline(pipeline) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 314, in execute_pipeline pipeline.communicate() File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/pipette/__init__.py", line 211, in communicate self.execute_process(process, pipe_parameters) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 162, in execute_process step_name = self.get_step_name(process.name) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 35, in name return self.parameters['name'] KeyError: 'name'</ERRORDESCRIPTION><ERRORTIME>201309172209</ERRORTIME><MODULEOUT>precluster</MODULEOUT>
<MODULEFILE>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/modules/run_pipes.sh</MODULEFILE><ERRORDESCRIPTION>Traceback (most recent call last): File "&lt;stdin&gt;", line 15, in &lt;module&gt; File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 307, in process_pipelines self.execute_pipeline(pipeline) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 314, in execute_pipeline pipeline.communicate() File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/pipette/__init__.py", line 212, in communicate self.execute_process(process, pipe_parameters) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 170, in execute_process super(BrainyPipe, self).execute_process(process, parameters) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/pipette/__init__.py", line 223, in execute_process process.execute(parameters) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/pipette/__init__.py", line 54, in execute self.put_on() File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 53, in put_on super(BrainyProcess, self).put_on() File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/pipette/__init__.py", line 61, in put_on self.parse_input() File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/pipette/__init__.py", line 35, in parse_input input_parameters = json.load(self.streams['input']) File "/usr/lib/python2.7/json/__init__.py", line 278, in load **kw) File "/usr/lib/python2.7/json/__init__.py", line 326, in loads return _default_decoder.decode(s) File "/usr/lib/python2.7/json/decoder.py", line 366, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end()) File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode raise ValueError("No JSON object could be decoded") ValueError: No JSON object could be decoded</ERRORDESCRIPTION><ERRORTIME>201309172210</ERRORTIME><MODULEOUT></MODULEOUT>
<MODULEFILE>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/modules/run_pipes.sh</MODULEFILE><ERRORDESCRIPTION>Traceback (most recent call last): File "&lt;stdin&gt;", line 15, in &lt;module&gt; File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 307, in process_pipelines self.execute_pipeline(pipeline) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 314, in execute_pipeline pipeline.communicate() File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/pipette/__init__.py", line 216, in communicate self.execute_process(process, pipe_parameters) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 170, in execute_process super(BrainyPipe, self).execute_process(process, parameters) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/pipette/__init__.py", line 227, in execute_process process.execute(parameters) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/pipette/__init__.py", line 59, in execute self.run() File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 117, in run self.submit() File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/CellProfiler.py", line 17, in submit submission_result = self.submit_job() AttributeError: 'PreCluster' object has no attribute 'submit_job'</ERRORDESCRIPTION><ERRORTIME>201309172213</ERRORTIME><MODULEOUT></MODULEOUT>
<MODULEFILE>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/modules/run_pipes.sh</MODULEFILE><ERRORDESCRIPTION>Traceback (most recent call last): File "&lt;stdin&gt;", line 15, in &lt;module&gt; File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 307, in process_pipelines self.execute_pipeline(pipeline) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 314, in execute_pipeline pipeline.communicate() File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/pipette/__init__.py", line 216, in communicate self.execute_process(process, pipe_parameters) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 170, in execute_process super(BrainyPipe, self).execute_process(process, parameters) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/pipette/__init__.py", line 227, in execute_process process.execute(parameters) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/pipette/__init__.py", line 59, in execute self.run() File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 117, in run self.submit() File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/CellProfiler.py", line 17, in submit submission_result = self.submit_job() AttributeError: 'PreCluster' object has no attribute 'submit_job'</ERRORDESCRIPTION><ERRORTIME>201309172214</ERRORTIME><MODULEOUT></MODULEOUT>
<MODULEFILE>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/modules/run_pipes.sh</MODULEFILE><ERRORDESCRIPTION>Traceback (most recent call last): File "&lt;stdin&gt;", line 15, in &lt;module&gt; File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 307, in process_pipelines self.execute_pipeline(pipeline) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 314, in execute_pipeline pipeline.communicate() File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/pipette/__init__.py", line 216, in communicate self.execute_process(process, pipe_parameters) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 170, in execute_process super(BrainyPipe, self).execute_process(process, parameters) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/pipette/__init__.py", line 227, in execute_process process.execute(parameters) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/pipette/__init__.py", line 59, in execute self.run() File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 117, in run self.submit() File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/CellProfiler.py", line 17, in submit submission_result = self.submit_job() AttributeError: 'PreCluster' object has no attribute 'submit_job'</ERRORDESCRIPTION><ERRORTIME>201309172217</ERRORTIME><MODULEOUT></MODULEOUT>
<MODULEFILE>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/modules/run_pipes.sh</MODULEFILE><ERRORDESCRIPTION>Traceback (most recent call last): File "&lt;stdin&gt;", line 15, in &lt;module&gt; File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 307, in process_pipelines self.execute_pipeline(pipeline) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 314, in execute_pipeline pipeline.communicate() File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/pipette/__init__.py", line 216, in communicate self.execute_process(process, pipe_parameters) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 170, in execute_process super(BrainyPipe, self).execute_process(process, parameters) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/pipette/__init__.py", line 227, in execute_process process.execute(parameters) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/pipette/__init__.py", line 59, in execute self.run() File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 117, in run self.submit() File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/CellProfiler.py", line 17, in submit submission_result = self.submit_job() AttributeError: 'PreCluster' object has no attribute 'submit_job'</ERRORDESCRIPTION><ERRORTIME>201309172218</ERRORTIME><MODULEOUT></MODULEOUT>
<MODULEFILE>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/modules/run_pipes.sh</MODULEFILE><ERRORDESCRIPTION>Traceback (most recent call last): File "&lt;stdin&gt;", line 15, in &lt;module&gt; File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 396, in process_pipelines self.execute_pipeline(pipeline) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 403, in execute_pipeline pipeline.communicate() File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/pipette/__init__.py", line 216, in communicate self.execute_process(process, pipe_parameters) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 259, in execute_process super(BrainyPipe, self).execute_process(process, parameters) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/pipette/__init__.py", line 227, in execute_process process.execute(parameters) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/pipette/__init__.py", line 59, in execute self.run() File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 206, in run self.submit() File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/CellProfiler.py", line 17, in submit submission_result = self.submit_job() TypeError: submit_job() takes at least 2 arguments (1 given)</ERRORDESCRIPTION><ERRORTIME>201309180136</ERRORTIME><MODULEOUT></MODULEOUT>
<MODULEFILE>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/modules/run_pipes.sh</MODULEFILE><ERRORDESCRIPTION>Traceback (most recent call last): File "&lt;stdin&gt;", line 15, in &lt;module&gt; File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 435, in process_pipelines for pipeline in self.pipelines: File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 351, in pipelines cls = self.get_class(definition['type']) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 339, in get_class module = __import__(module_name, {}, {}, [class_name]) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/CellProfiler.py", line 78 ^ IndentationError: expected an indented block</ERRORDESCRIPTION><ERRORTIME>201309191708</ERRORTIME><MODULEOUT></MODULEOUT>
<MODULEFILE>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/modules/run_pipes.sh</MODULEFILE><ERRORDESCRIPTION>Traceback (most recent call last): File "&lt;stdin&gt;", line 15, in &lt;module&gt; File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 444, in process_pipelines self.execute_pipeline(pipeline) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 451, in execute_pipeline pipeline.communicate() File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/pipette/__init__.py", line 218, in communicate self.execute_process(process, pipe_parameters) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 307, in execute_process super(BrainyPipe, self).execute_process(process, parameters) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/pipette/__init__.py", line 229, in execute_process process.execute(parameters) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/pipette/__init__.py", line 59, in execute self.put_on() File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/CellProfiler.py", line 46, in put_on super(PreCluster, self).put_on() File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 192, in put_on os.makedirs(self.process_path) File "/usr/lib/python2.7/os.py", line 157, in makedirs mkdir(name, mode) OSError: [Errno 17] File exists: '../project/PIPES/test'</ERRORDESCRIPTION><ERRORTIME>201309191727</ERRORTIME><MODULEOUT></MODULEOUT>
<MODULEFILE>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/modules/run_pipes.sh</MODULEFILE><ERRORDESCRIPTION>Traceback (most recent call last): File "&lt;stdin&gt;", line 15, in &lt;module&gt; File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 454, in process_pipelines for pipeline in self.pipelines: File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 370, in pipelines cls = self.get_class(definition['type']) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 358, in get_class module = __import__(module_name, {}, {}, [class_name]) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/CellProfiler.py", line 5, in &lt;module&gt; from brainy import make_path ImportError: cannot import name make_path</ERRORDESCRIPTION><ERRORTIME>201309191745</ERRORTIME><MODULEOUT></MODULEOUT>
<MODULEFILE>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/modules/run_pipes.sh</MODULEFILE><ERRORDESCRIPTION>Traceback (most recent call last): File "&lt;stdin&gt;", line 15, in &lt;module&gt; File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 444, in process_pipelines self.execute_pipeline(pipeline) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 451, in execute_pipeline pipeline.communicate() File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/pipette/__init__.py", line 218, in communicate self.execute_process(process, pipe_parameters) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 307, in execute_process super(BrainyPipe, self).execute_process(process, parameters) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/pipette/__init__.py", line 229, in execute_process process.execute(parameters) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/pipette/__init__.py", line 59, in execute self.put_on() File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/CellProfiler.py", line 47, in put_on super(PreCluster, self).put_on() File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 192, in put_on os.makedirs(self.process_path) File "/usr/lib/python2.7/os.py", line 157, in makedirs mkdir(name, mode) OSError: [Errno 17] File exists: '../project/PIPES/test'</ERRORDESCRIPTION><ERRORTIME>201309191746</ERRORTIME><MODULEOUT></MODULEOUT>
<MODULEFILE>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/modules/run_pipes.sh</MODULEFILE><ERRORDESCRIPTION>Traceback (most recent call last): File "&lt;stdin&gt;", line 15, in &lt;module&gt; File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 444, in process_pipelines self.execute_pipeline(pipeline) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 451, in execute_pipeline pipeline.communicate() File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/pipette/__init__.py", line 218, in communicate self.execute_process(process, pipe_parameters) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 307, in execute_process super(BrainyPipe, self).execute_process(process, parameters) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/pipette/__init__.py", line 229, in execute_process process.execute(parameters) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/pipette/__init__.py", line 59, in execute self.put_on() File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/CellProfiler.py", line 47, in put_on super(PreCluster, self).put_on() File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 192, in put_on os.makedirs(self.process_path) File "/usr/lib/python2.7/os.py", line 157, in makedirs mkdir(name, mode) OSError: [Errno 17] File exists: '../project/PIPES/test'</ERRORDESCRIPTION><ERRORTIME>201309191747</ERRORTIME><MODULEOUT></MODULEOUT>
<MODULEFILE>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/modules/run_pipes.sh</MODULEFILE><ERRORDESCRIPTION>Traceback (most recent call last): File "&lt;stdin&gt;", line 15, in &lt;module&gt; File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 443, in process_pipelines for pipeline in self.pipelines: File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 359, in pipelines cls = self.get_class(definition['type']) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 347, in get_class module = __import__(module_name, {}, {}, [class_name]) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/CellProfiler.py", line 5, in &lt;module&gt; from brainy import make_path ImportError: cannot import name make_path</ERRORDESCRIPTION><ERRORTIME>201309191753</ERRORTIME><MODULEOUT></MODULEOUT>
<MODULEFILE>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/modules/run_pipes.sh</MODULEFILE><ERRORDESCRIPTION>Traceback (most recent call last): File "&lt;stdin&gt;", line 15, in &lt;module&gt; File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 443, in process_pipelines for pipeline in self.pipelines: File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 359, in pipelines cls = self.get_class(definition['type']) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 347, in get_class module = __import__(module_name, {}, {}, [class_name]) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/CellProfiler.py", line 5, in &lt;module&gt; from brainy import make_path ImportError: cannot import name make_path</ERRORDESCRIPTION><ERRORTIME>201309191753</ERRORTIME><MODULEOUT></MODULEOUT>
<MODULEFILE>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/modules/run_pipes.sh</MODULEFILE><ERRORDESCRIPTION>Traceback (most recent call last): File "&lt;stdin&gt;", line 15, in &lt;module&gt; File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 444, in process_pipelines self.execute_pipeline(pipeline) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 451, in execute_pipeline pipeline.communicate() File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/pipette/__init__.py", line 218, in communicate self.execute_process(process, pipe_parameters) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 307, in execute_process super(BrainyPipe, self).execute_process(process, parameters) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/pipette/__init__.py", line 229, in execute_process process.execute(parameters) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/pipette/__init__.py", line 59, in execute self.put_on() File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/CellProfiler.py", line 47, in put_on super(PreCluster, self).put_on() File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 192, in put_on os.makedirs(self.process_path) File "/usr/lib/python2.7/os.py", line 157, in makedirs mkdir(name, mode) OSError: [Errno 17] File exists: '../project/PIPES/test'</ERRORDESCRIPTION><ERRORTIME>201309191753</ERRORTIME><MODULEOUT></MODULEOUT>
<MODULEFILE>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/modules/run_pipes.sh</MODULEFILE><ERRORDESCRIPTION>Traceback (most recent call last): File "&lt;stdin&gt;", line 15, in &lt;module&gt; File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 444, in process_pipelines self.execute_pipeline(pipeline) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 451, in execute_pipeline pipeline.communicate() File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/pipette/__init__.py", line 218, in communicate self.execute_process(process, pipe_parameters) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 307, in execute_process super(BrainyPipe, self).execute_process(process, parameters) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/pipette/__init__.py", line 229, in execute_process process.execute(parameters) File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/pipette/__init__.py", line 59, in execute self.put_on() File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/CellProfiler.py", line 47, in put_on super(PreCluster, self).put_on() File "/home/yy/dev/imls/iBRAIN/iBRAIN/lib/python/brainy/pipes/__init__.py", line 192, in put_on os.makedirs(self.process_path) File "/usr/lib/python2.7/os.py", line 157, in makedirs mkdir(name, mode) OSError: [Errno 17] File exists: '../project/PIPES/test'</ERRORDESCRIPTION><ERRORTIME>201309191753</ERRORTIME><MODULEOUT></MODULEOUT>
<MODULEFILE>./core/modules/check_image_set.sh</MODULEFILE><ERRORDESCRIPTION>find: warning: you have specified the -maxdepth option after a non-option argument -type, but options are not positional (-maxdepth affects tests specified before it as well as those specified after it). Please specify options before other arguments.</ERRORDESCRIPTION><ERRORTIME>201310291550</ERRORTIME><MODULEOUT>&lt;!- COMPLETEFILECHECK=0 -&gt; &lt;!- TIFFDIRLASTMODIFIED=1 -&gt; &lt;!- TIFFCOUNT=0 -&gt; &lt;status action="check_image_set"&gt;paused &lt;message&gt; Paused because the TIFF directory contains no tif images. &lt;/message&gt; &lt;/status&gt;</MODULEOUT>
<MODULEFILE>/home/yy/dev/imls/iBRAIN/iBRAIN/tests/mock/root/core/modules/run_pipes.sh</MODULEFILE><ERRORDESCRIPTION>Traceback (most recent call last): File "&lt;stdin&gt;", line 5, in &lt;module&gt; ImportError: No module named brainy.pipes</ERRORDESCRIPTION><ERRORTIME>201310291755</ERRORTIME><MODULEOUT></MODULEOUT>
